/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CurrencyExchangeRate } from '../models/currency-exchange-rate';
export interface Rates {
  vcbRates?: Array<CurrencyExchangeRate>;
  vibRates?: Array<CurrencyExchangeRate>;
}
