/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Transaction {
  date?: string;
  description?: string;
  id?: number;
  lastModified?: string;
  value?: number;
}
