/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { YearTotal } from '../../models/year-total';

export interface GetAllYearTotals$Params {
}

export function getAllYearTotals(http: HttpClient, rootUrl: string, params?: GetAllYearTotals$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<YearTotal>>> {
  const rb = new RequestBuilder(rootUrl, getAllYearTotals.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<YearTotal>>;
    })
  );
}

getAllYearTotals.PATH = '/app/AccountManagement/api/v1/transactions';
